### ISSUE TITLE
[BUG] example response not showing line breaks correctly

### ISSUE THREAD

**Issue by Azraelless** [BRIKEV/express-jsdoc-swagger#100]
**Describe the bug**
Example responses shows line breaks as `/n` breaking any readability of it

**To Reproduce**
``` 
   * @example response - 200 - example with group-by-day=false
   * [
   *   {
   *     name: 'foo',
   *     bar: 1241
   *   }
   * ]
```

**Expected behavior**
Expected "Indentation and breaklines will be preserved in Swagger UI" as described in the docs.

**Screenshots**
Here's how it looks in UI
![image](https://user-images.githubusercontent.com/24431227/97887663-dee43480-1d32-11eb-93ec-ecb192896f66.png)

 - Version 1.1.0

**Comment by Brenndoerfer** [comment]
Experiencing the same. Tested with examples

**Comment by kevinccbsg** [comment]
Hi @Azraelless and @Brenndoerfer,

As @Brenndoerfer said we are sending the info as the OpenAPI says so we think there is a problem related to the `swagger-ui` library. We could only reproduce this by adding the `yaml` in the https://editor.swagger.io/ website If you use the page that this library renders you can see the example in the right format like in this screenshot.

<img width="626" alt="Screen Shot 2020-11-08 at 17 49 05" src="https://user-images.githubusercontent.com/12685053/98471158-b94fa300-21ea-11eb-8366-0dee3917990f.png">


We created an issue in the `swagger-ui` library https://github.com/swagger-api/swagger-ui/issues/6595 to track this or see if there is another solution 🤔

**Comment by thuydx55** [comment]
Hi, I've created PR #104 to solve this problem
