### ISSUE TITLE
How to create multiple swagger docs path for difference purpose?

### ISSUE THREAD

**Issue by thuydx55** [BRIKEV/express-jsdoc-swagger#106]
In my context, I want to create docs for User APIs and the other one for Admin APIs. Is it possible to do that?

**Comment by kevinccbsg** [comment]
Hi @thuydx55, I don't think that's possible. This only renders one swagger in the specific route you can set in the configuration.

**Comment by kevinccbsg** [comment]
Hi, @thuydx55 thanks to this [PR](https://github.com/BRIKEV/express-jsdoc-swagger/pull/125) your request will be possible. 👍 

As soon as it is merged we will create a new release.
