### ISSUE TITLE
Export Swagger definition

### ISSUE THREAD

**Issue by alexwaibel** [BRIKEV/express-jsdoc-swagger#114]
**Is your feature request related to a problem? Please describe.**
I currently use this package for an express API which does not offer a publicly hosted instance so we have nowhere to serve the documentation endpoint from.

**Describe the solution you'd like**
I would like to be able to export the generated swagger yml file so that I can use it with my CICD to host the docs on GH pages. [This repo](https://github.com/peter-evans/swagger-github-pages) works for such hosting and only needs the swagger definition.

**Describe alternatives you've considered**
I'm considering switching to other Swagger jsdoc libraries for this, but I much prefer the format of the docstrings which this project uses.

**Comment by kevinccbsg** [comment]
Hi @alexwaibel ,

You already have an option to get the JSON result of your endpoints. 👍 You can check out this [example](https://github.com/BRIKEV/express-jsdoc-swagger/blob/master/examples/eventEmitter/index.js).

In that example, if you define one variable you can subscribe to some events like `finish`. That event exposes the JSON OpenAPI result.

Therefore, you can do this:

```js
// Define variable
const listener = expressJSDocSwagger(app)(options);

listener.on('finish', swaggerObject => {
  console.log(JSON.stringify(swaggerObject, null, 2)); // This will print JSON OpenAPI result
});
```

Then you will get the OpenAPI JSON output and that result. You can use that result to generate a YAML maybe using a script to parse the JSON to YAML ([json-to-yaml](https://www.npmjs.com/package/json-to-pretty-yaml)) and add it to your CI. Right now, we don't provide an option to generate the YAML result but only JSON. Maybe we could consider it for future releases.

I hope this helps you. You can find more info on our [docs page](https://brikev.github.io/express-jsdoc-swagger-docs/#/eventEmitter).

**Comment by kdankert** [comment]
Another option would be to expose it using the feature update in 1.3.0.

Just set exposeApiDocs to true in your project and apiDocsPath to the correct path (defaults to /v3/api-docs). 

See https://www.npmjs.com/package/express-jsdoc-swagger#usage for reference.
