### ISSUE TITLE
Add a file upload example

### ISSUE THREAD

**Issue by LuizFelipeNeves** [BRIKEV/express-jsdoc-swagger#117]
**Is your feature request related to a problem? Please describe.**
i don't know how to add file upload on a route.

**Describe the solution you'd like**
Add in documentation a file upload example

**Comment by kevinccbsg** [comment]
Hi @LuizFelipeNeves,

This is our [Form data example](https://github.com/BRIKEV/express-jsdoc-swagger/blob/master/examples/requestBody/formdata.js) where you can find how you can add a file upload option. 👍 

<img width="649" alt="Screenshot 2020-11-30 at 22 38 25" src="https://user-images.githubusercontent.com/12685053/100669409-9f266200-335d-11eb-9d9a-4220abe9c9a1.png">

If there is another different configuration let us know a YAML example. I hope the previous link help you with this 👍
