### ISSUE TITLE
JSDoc optional syntax instead of `.required`

### ISSUE THREAD

**Issue by lunix33** [BRIKEV/express-jsdoc-swagger#120]
**Is your feature request related to a problem? Please describe.**

I mostly noticed the issue when using `@typedef`, since comments on `app.use` tend to be quite meaningless when it comes to the IDE type discovery.

Types which uses JSDoc optional syntax aren't shown in the Swagger UI.

Also the current way to define required parameters or properties causes issues with code editor type detection.
When adding `.required` to the name of the parameter/property VSCode isn't able to detect the property type anymore.

**Describe the solution you'd like**

A solution would be to use the default JSDoc optional syntax.

The parameter definition would go from `@param {number} myNum This is my optional number` to `@param {number} [myNum] This is my optional number` for optional parameters and from `@param {number} myNum.required This is my optional number` to `@param {number} myNum This is my optional number` for required parameters.

**Describe alternatives you've considered**

Currently we're just keeping all the parameters/properties optional (not adding `.required`) since it would break the type detection.

**Additional context**

![image](https://user-images.githubusercontent.com/9218179/101825657-e51cbc00-3afb-11eb-95f2-771099dab025.png)

As you can see VSCode doesn't detect one of the properties since it think the property name is `required`.

**Comment by kevinccbsg** [comment]
Hi @lunix33,

We are considering your proposal but right now I think it would be a breaking change and a lot of the code should be changed 🤔 We could not work on this these months but we are considering creating a v2 branch to start doing some POCs about this idea.

We will try to keep this issue with more info 👍 thanks for the feedback/suggestion.
