### ISSUE TITLE
[BUG] Example request rendering as string instead of object

### ISSUE THREAD

**Issue by Gavin152** [BRIKEV/express-jsdoc-swagger#132]
**What is happening**
I try to show an example request body object for a POST request. I use the examples that can be found [here](https://github.com/BRIKEV/express-jsdoc-swagger/blob/master/examples/requestBody/withExamples.js). However, the example is shown as a string: ```"{\n  \"title\": \"Bury The Light\",\n  \"artist\": \"Casey Edwards ft. Victor Borba\",\n  \"year\": 2020\n}"```

![image](https://user-images.githubusercontent.com/37634936/108349743-a71ad300-71e3-11eb-988b-2e47446d9e13.png)

Once I change the selection in the combo box to "other payload example" and back to "payload example" again, it displays the example correctly:

![image](https://user-images.githubusercontent.com/37634936/108350000-f234e600-71e3-11eb-994e-75ee24e8e6b3.png)

When I'm only using one example, there's no way to get it to display properly as in the second screenshot.

**To Reproduce**
These are the JS Doc Comments, that I'm using:
```/**
 * A song
 * @typedef {object} Song
 * @property {string} title.required - The title
 * @property {string} artist - The artist
 * @property {integer} year - The year - int64
 */

/**
 * POST /api/v1/song
 * @param {Song} request.body.required - song info
 * @return {object} 200 - song response
 * @return {object} 400 - Bad request response
 * @example request - payload example
 * {
 *   "title": "Bury The Light",
 *   "artist": "Casey Edwards ft. Victor Borba",
 *   "year": 2020
 * }
 * @example request - other payload example
 * {
 *   "title": "The war we made",
 *   "artist": "Red",
 *   "year": 2020
 * }
 */
```

this is my environment:
NodeJS v14.10.0
WSL2 Ubuntu

I am using this in a TypeScript app, in case that's of relevance (which I doubt, since everything else is functioning fine).

I don't know if that's a bug, or whether I'm simply oblivious to an error of mine. Any pointers would be greatly appreciated.
THANKS

**Comment by kevinccbsg** [comment]
Hi @Gavin152, you're right. I think there is an issue with the library we are using to render that content [swagger-ui-express](https://www.npmjs.com/package/swagger-ui-express).

We will try to update in the `package-lock.json` or we will migrate to [this one](https://www.npmjs.com/package/swagger-ui-express-updated) which is the same but updated with the latest version of Swagger UI.

**Comment by kevinccbsg** [comment]
Hi @Gavin152,

After #126 was merged we are not being able to replicate this issue so I think that dependency was causing the issue. I'll attach some screenshots of our Example.

<img width="527" alt="Screenshot 2021-04-18 at 14 02 45" src="https://user-images.githubusercontent.com/12685053/115144768-c2bd2100-a04e-11eb-807b-77b670033b09.png">


<img width="524" alt="Screenshot 2021-04-18 at 14 03 46" src="https://user-images.githubusercontent.com/12685053/115144793-e718fd80-a04e-11eb-8cf2-1fda77008eed.png">

I'm closing this issue, so I'd recommend you update your version 👍  If it stills a problem you can re-open this issue and as you did before it would be great to have an example 😃

**Comment by nikspyratos** [comment]
FWIW, I have the same issue as OP, on the latest version of both this and 4.6.3 of `swagger-ui-express`, _and_ switching between the two examples doesn't fix the rendering. Tried overriding `swagger-ui-express` to ^5.0 but same issue.

I'm not usually in express/JS land so not sure where this issue belongs 😅
