### ISSUE TITLE
Hiding components

### ISSUE THREAD

**Issue by NolanChan** [BRIKEV/express-jsdoc-swagger#137]
Hi! Is there any way currently to hide schemas? My use case is to hide schemas from the general list view (to prevent clutter), but still reference them inside other schemas

**Comment by kevinccbsg** [comment]
Hi @NolanChan as you can see in this PR #150 you can hide the schemas passing the swagger UI options.  https://github.com/BRIKEV/express-jsdoc-swagger/blob/master/examples/configuration/swaggerOptions.js#L31 👍
