### ISSUE TITLE
[BUG] Swagger UI response TYPE is giving html  instead of json response 

### ISSUE THREAD

**Issue by Danish-Ali097** [BRIKEV/express-jsdoc-swagger#138]
**Describe the bug**
I wanted to have a documentation for my API. Im doing every thing described in the docs but it is not giving me mty expected result

**Expected behavior**
the expected output should be a JSON object but it gives me a html markup in response

**Screenshots**
![github SwaggerUI](https://user-images.githubusercontent.com/50976119/110424310-69afb400-80c4-11eb-985a-df340a845273.png)

**Desktop (please complete the following information):**
 - OS:[ Windows 10 Pro]
 - Version [20H2]

**Additional context**

**Comment by kevinccbsg** [comment]
Hi @Danish-Ali097,

The library only documents your OpenAPI definitions and generates the UI. Therefore, if the API, in this case, your `http://localhost:3000/api/admin/login`, does not implement that feature it won't return the expected documented result. 

You have to double-check your API if it is returning JSON or HTML when you receive an error. This Library is not going to generate the Endpoint logic.
