### ISSUE TITLE
[BUG] no way to create multiple instances of jsdocSwagger for different apis in a single application

### ISSUE THREAD

**Issue by paulish** [BRIKEV/express-jsdoc-swagger#167]
**Describe the bug**
The second call to `expressJSDocSwagger(app)` returns the same instance as the first call.

**To Reproduce**

I wrote the following code to create api:
```javascript
 const initRoutes = (basePath, docUri, routes) => new Promise(resolve => {
        const options = {
            info: {
                version: '2.0.0',
                title: 'some title',
                description: 'some description'
            },
            baseDir: __dirname,
            filesPattern: `${basePath}/*.js`,
            swaggerUIPath: docUri,
            apiDocsPath: `/v3${docUri}`,
            exposeSwaggerUI: true,
            exposeApiDocs: true,
            notRequiredAsNullable: true,
            swaggerUiOptions: {}
        };
        const instance = expressJSDocSwagger(app)(options);
        instance.on('finish', data => {
            init(data);
            for (const route of routes)
                app.use(route, require(`${basePath}${route === '/' ? '/index' : route}`));

            resolve();
        });
    });
```

And I call it this way:
```javascript
   // regular api
   await initRoutes('./routes', '/api-docs', [
        '/', '/auth', '/clinic', ...
    ]);
    // doctor api
    await initRoutes('./doctorRoutes', '/api-docs-doctor', [
        '/doctor'
    ]);
```

The second call runs 'finish' event twice for the first group of routes and for the second. This happens since `swaggerEvents.js` does not create the second instance if instance has been already created:
```javascript
const swaggerEvents = () => {
  if (api) return api; // <-- this line
  ...
```

**Expected behavior**

A new instance should be created.

**Comment by kevinccbsg** [comment]
Hi, @paulish I think you're totally right.

We have to fix that in the swaggerEvents file as we are using always the same instance.

Apart from that, we have an example about this here -> https://github.com/BRIKEV/express-jsdoc-swagger/tree/master/examples/configuration/multipleInstance

Does that example help you?

We will change that single instance in the next release 👍
