### ISSUE TITLE
[Feature Request] support for operationId

### ISSUE THREAD

**Issue by nums** [BRIKEV/express-jsdoc-swagger#169]
It can be very useful to support it : 
https://swagger.io/docs/specification/paths-and-operations/

**Comment by kevinccbsg** [comment]
Hi @nums,

Thanks for the issue, but we don't understand what you mean. Do you mean the paths and methods like these?

<img width="613" alt="Screenshot 2021-07-20 at 00 13 42" src="https://user-images.githubusercontent.com/12685053/126234165-42f8f274-5858-4865-9b65-39b75d51acee.png">

We already support that 😅 could you provide a YML example? 🤔

**Comment by nums** [comment]
Hi @kevinccbsg 

Thanks for your reply, I was talking about `operationId` : 
![image (67)](https://user-images.githubusercontent.com/274268/126284527-e97efb3f-ab8e-401e-8356-fee340d4ba99.png)

I tried :  `* @operationId getInfo` but nothing change in my generated swagger file

**Comment by kevinccbsg** [comment]
Hi @nums,

I think you're right we don't have support for that. We will consider for future releases.

I'm not sure about this one. We will test it 👍 
```
* @operationId getInfo
```
