### ISSUE TITLE
[BUG] When exposing the api-docs (options.exposeApiDocs) there's a host flag which is not openapi3.0 valid

### ISSUE THREAD

**Issue by Blacklegions** [BRIKEV/express-jsdoc-swagger#174]
**Describe the bug**
When accessing the swagger page, a host parameter is added to the SwaggerObject. This parameter is then shown on the api-docs page which is not OpenApi3.0 complient. Which means we can't copy the api-docs into a client generator.

**To Reproduce**
Go on the swagger page, and afterwards on the api-docs page. It will be the last paramenter at the bottom.
If you go directly on the api-docs page without passing by the swagger page first the parameter will not be there (On server start)

**Expected behavior**
The host parameter should not be there in the api-docs page.

**Screenshots**
http://localhost:3000/v3/api-docs
![image](https://user-images.githubusercontent.com/19292086/128083797-c602346b-a8e4-460d-b0df-a14292f483ed.png)

Swagger io validator [https://editor.swagger.io/]
![image](https://user-images.githubusercontent.com/19292086/128083870-46c8c3e6-2743-4e0b-8f76-56cbc3600eba.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by kevinccbsg** [comment]
Hi @Blacklegions,

Oh, you mean with the export in the endpoint. We normally get that info using the event emitter https://brikev.github.io/express-jsdoc-swagger-docs/#/eventEmitter but I think we can solve your 🐛 

We will keep this issue updated. It should not be hard, we have to filter the object we exposed.

**Comment by Blacklegions** [comment]
Thank you for your quick response. I will take a look

**Comment by kevinccbsg** [comment]
I will do a release now I hope that solves the issue. Please don't hesitate to re-open in case it is not fixed.
