### ISSUE TITLE
Add support for `@augments`/`@extends` tag

### ISSUE THREAD

**Issue by HigherOrderLogic** [BRIKEV/express-jsdoc-swagger#219]
**Is your feature request related to a problem? Please describe.**
When I'm documenting my API, there's are lots of partial classes and "full" classes that are based on those. This results in lots of duplicate code and make the file very hard to maintain.

**Describe the solution you'd like**
My solution is add support for the `@augments`/`@extends` tag. Example:
```js
/**
 * Foo
 * @typedef {object} Foo
 * @property {number} id.required - Object's id
 */

/**
 * FooBar
 * @typedef {object} FooBar
 * @augments Foo
 * @property {string} name.required - Object's name
 */
 ```
 The result would look like the below image.

![image](https://user-images.githubusercontent.com/73709188/170067433-39a1dd76-df88-4dc4-a9be-fa2be72cd246.png)

**Describe alternatives you've considered**
Maybe `@inheritdoc` is ok too.

**Additional context**
See the first field.

**Comment by sbamniya** [comment]
+1

**Comment by HigherOrderLogic** [comment]
Thanks for your support!
