### ISSUE TITLE
[BUG] Unable to render this definition

### ISSUE THREAD

**Issue by fakhirarslan** [BRIKEV/express-jsdoc-swagger#226]
**Describe the bug**
Unable to render this definition
The provided definition does not specify a valid version field.

Please indicate a valid Swagger or OpenAPI version field. Supported version fields are swagger: "2.0" and those that match openapi: 3.0.n (for example, openapi: 3.0.0).

**Expected behavior**
Should open the swagger UI with API doc

**Screenshots**
![image](https://user-images.githubusercontent.com/26690349/177996585-2be82f0e-f12a-4738-bdb7-7318ea1404fc.png)
![image](https://user-images.githubusercontent.com/26690349/177996653-f0472c45-e6b5-4177-ae09-072594f2a6dd.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Additional context**
I've tried to add `swagger: '2.0'` and `openapi: '3.0.0'`, but it doesn't work.

**Comment by kevinccbsg** [comment]
Hi @fakhirarslan thanks for reporting.

We only support `openapi: '3.0.0'`. I try to replicate your error based on that screenshot and I don't get that message. Could you share more lines of your code?
