### ISSUE TITLE
Authorization Header [BUG]

### ISSUE THREAD

**Issue by jcdesignweb** [BRIKEV/express-jsdoc-swagger#229]
Hi everyone!
I am try to send the Authorization token for all my endpoints of my API. But the server side does not receive the header with name : "**Authorization**" or "**authorization**". The weird is if I try to send any other value as a Header param this works fine.

this is my code:
`/**
* PUT /v1/users/password
* @summary it updates the User password
* @param {string} authorization.header.required - authorization Header
* @param {UserPassword} request.body.required - UserPassword - application/json
* @tags Users
* @return {} 200 - success response - application/json
*/`

**_Environment values:_**
**Language**: Typescript
**Node version**: v18.0.0
**express-jsdoc-swagger version**: 1.8.0

Would should I send the Authorization as a different way?

TIA

**Comment by iisalazar** [comment]
Any updates on this?

**Comment by ronaldborla** [comment]
@jcdesignweb You have to set the `security` option:

```
  ...
  security: {
    BearerAuth: {
      type: 'http',
      scheme: 'bearer',
    },
  }
  ...
```
Then in your route comment, add the `@security` tag:

```
PUT /v1/users/password
@security BearerAuth
...
```
This will show up on your docs:
![image](https://user-images.githubusercontent.com/5573684/216756915-81084a8e-0e97-449a-a3f4-3d33dffdd66f.png)

You will have to enter the authorization token that you need for your endpoints:

![image](https://user-images.githubusercontent.com/5573684/216757059-a3d0ee67-6367-4cd8-a931-0c63650e687b.png)

You'll know that the endpoint needs authorization if it has this icon next to it:
![image](https://user-images.githubusercontent.com/5573684/216757003-e24a91da-f478-48d1-a61b-6b954f3a23c5.png)

Then you can execute your API call normally, the `Authorization` header will automatically be filled, so you don't need to add this line:
```
@param {string} authorization.header.required - authorization Header
```

**Comment by jcdesignweb** [comment]
@ronaldborla thanks Ronal, I think it was a mistake from my side. I tested this again and it works. I will close the ticket.
