### ISSUE TITLE
[Enhancement] Provide support to oneOf, anyOf...

### ISSUE THREAD

**Issue by kevinccbsg** [BRIKEV/express-jsdoc-swagger#36]
We still need to provide support to [oneOf, anyOf, allOff, not](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/) swagger options.

We need to decide the API we want to provide for these methods. So this question should be answered before we start working on this.

## Questions

- How should we define in the JSDOC these methods?

**Comment by kevinccbsg** [comment]
To answer that question @bri06 and I decided to use this format.

```js
/**
 * Generator options
 * @typedef {Object} Options
 * @property {oneof(Song|Album)} title - The title
 */
```

**Comment by bri06** [comment]
Finally `{oneof(Song|Album)}` was not possible, so we opted for the next one:
/**
 * Generator options
 * @typedef {Object} Options
 * @property {oneof|Song|Album} title - The title
 */
