### ISSUE TITLE
unsupport method: post,  header:application/x-www-form-urlencoded,  body: name=1&code=2

### ISSUE THREAD

**Issue by chenjiangui** [BRIKEV/express-jsdoc-swagger#86]
rt, doc only show body is json.

**Comment by kevinccbsg** [comment]
Hi @chenjiangui,

We open a new PR #87 to add an example of this. Is that the example you want to see in the examples folder?

You could also have a look in our [Docs page](https://brikev.github.io/express-jsdoc-swagger-docs/#/requestBody). 👍

**Comment by chenjiangui** [comment]
Thanks, it's Ok.  But this example need define a model. Has provide simple usage like that? sometimes i don't want define a model
```
/**
 * POST /api/v1/song
 * @param {string} id.form.required
 * @param {string} title.form.required
 * @produce application/x-www-form-urlencoded
 * @return {object} 200 - song response
 */
```

**Comment by kevinccbsg** [comment]
@chenjiangui you're right. We will add for the next release. 👍
