### ISSUE TITLE
Example request and response

### ISSUE THREAD

**Issue by drtobbyas** [BRIKEV/express-jsdoc-swagger#89]
How to add Example request and response to an endpoint. When writing API documentation, you would usually want to provide your users with sample request body to guide how the request payload should be constructed and formatted and also provide at least a sample returned response to showcase the format of the response 

**Describe the solution you'd like**
/**
*@example  {requestBody} - a sample request body
 {
          "username": "LA-AM-0001",
          "password": "PMNmj@123",
          "firstName": "segufkn",
          "lastName": "IDEklmhj",
          "dob": "2000-07-08",
          "gender": "Male",
          "role": "master-agent",
          "phone": {
            "code": "234",
            "number": "807489388"
          }
*@example  {responseBody} - a sample request body
{
          "status": true,
          "message": "user registered successfully",
          "data": {
            "username": "LA-AM-0001",
            "firstName": "segufkn",
            "lastName": "IDEklmhj",
            "dob": "04-26-202",
            "gender": "Male",
            "role": "master-agent",
            "phone": {
              "code": "234",
              "number": "807489388"
            },
            "wallet": {
              "balance": 20000,
              "ledgerBalance": 20000,
              "trust": 0
            }
          }
        }
*/

**Comment by kevinccbsg** [comment]
Hi @drtobbyas,

This is a great idea, we are not pretty sure about the implementation you commented 🤔 but definitely, that would be included in the next release. 🚀 

When we define the way this will be shown we'll let you know about it in this issue.
