### ISSUE TITLE
example for request header 

### ISSUE THREAD

**Issue by juicycool92** [BRIKEV/express-jsdoc-swagger#95]
**Is your feature request related to a problem? Please describe.**

so my API is quite lots of required header for each request. 
also sometime response have headers too, but this topic is not fit for this thread i guess.

So far I search this repo's example, n I did found how to make request header, luckily.

![image](https://user-images.githubusercontent.com/12273678/97654132-a3810600-1aa5-11eb-8620-395c02be7527.png)

```
/**
     *
     * POST /board/write
     * @summary 게시판 작성 메소드.
     * @tags board
     * @param {string} x-lang.header.required - ko
     * @param {string} x-access-token.header.required - access토큰
     * @param {string} x-refresh-token.header.required - refresh토큰
     * @param {Req_board_write} request.body.required - song info
     * @return {testType} 200 - success response - application/json
     * @example request - payload example
     * {
     *   "seqUser" : 0,
     *   "boardTitle" : "Hello world",
     *   "boardContext" : "<h1>Hello world</h1>",
     *   "boardType" : 1
     * }
     */
```
<above image and code is what i did find out so far>

I guess you guys assume that my header's are might be using all of my restAPI's. 
yes, those headers are pretty much everywhere in my project.

and its so hard that I have to copy-paste every single try-out. its so painful.

therefore I expect `@example` for request header also.
 
**Describe the solution you'd like**

add another annotation tag for request header example 
eg)

```
/**
     *
     * POST /board/write
     * @summary 게시판 작성 메소드.
     * @tags board
     * @param {string} x-lang.header.required - ko
     * @param {string} x-access-token.header.required - access토큰
     * @param {string} x-refresh-token.header.required - refresh토큰
     * @param {Req_board_write} request.body.required - song info
     * @return {testType} 200 - success response - application/json
     * @example request.body - payload example
     * {
     *   "seqUser" : 0,
     *   "boardTitle" : "Hello world",
     *   "boardContext" : "<h1>Hello world</h1>",
     *   "boardType" : 1
     * }
     * @example request.header - example headers
     * {
     *   "x-access-token" : "Foo",
     *   "x-refresh-token" : "Bar",
     *   "x-lang" : "Faz"
     * }
     */
```

**Describe alternatives you've considered**

or extends example for fillable header
eg)

```
/**
     *
     * POST /board/write
     * @summary 게시판 작성 메소드.
     * @tags board
     * @param {string} x-lang.header.required - ko
     * @param {string} x-access-token.header.required - access토큰
     * @param {string} x-refresh-token.header.required - refresh토큰
     * @param {Req_board_write} request.body.required - song info
     * @return {testType} 200 - success response - application/json
     * @example request - payload example
     * {
     *  "header" : {
     *     "x-access-token" : "Foo",
     *     "x-refresh-token" : "Bar",
     *     "x-lang" : "Faz"
     *   }
     *   "body" : {
     *     "seqUser" : 0,
     *     "boardTitle" : "Hello world",
     *     "boardContext" : "<h1>Hello world</h1>",
     *     "boardType" : 1
     *   }
     * }
     */
```

**Additional context**
or maybe there is already reqeust header example, 
i dunno where to find.
help me out will ya?

**Comment by kevinccbsg** [comment]
Hi @juicycool92,

Right now you can add headers for the request [like this example](https://github.com/BRIKEV/express-jsdoc-swagger/blob/master/examples/parameters/headers.js) as you mentioned in this issue. However, for responses we currently don't have support for that with the comments but you can use our [merge option](https://brikev.github.io/express-jsdoc-swagger-docs/#/merge). Maybe that can help you to solve your issue in the meantime.

For the response headers, there is already an issue and a discussion on the best way to create comments in [this issue](https://github.com/BRIKEV/express-jsdoc-swagger/issues/92).

We will keep this issue to track the header's examples feature progress. I don't think there is a way to create those examples right now. 🤔 we will have a look. 👍

**Comment by juicycool92** [comment]
> 
> 
> Hi @juicycool92,
> 
> Right now you can add headers for the request [like this example](https://github.com/BRIKEV/express-jsdoc-swagger/blob/master/examples/parameters/headers.js) as you mentioned in this issue. However, for responses we currently don't have support for that with the comments but you can use our [merge option](https://brikev.github.io/express-jsdoc-swagger-docs/#/merge). Maybe that can help you to solve your issue in the meantime.
> 
> For the response headers, there is already an issue and a discussion on the best way to create comments in [this issue](https://github.com/BRIKEV/express-jsdoc-swagger/issues/92).
> 
> We will keep this issue to track the header's examples feature progress. I don't think there is a way to create those examples right now. 🤔 we will have a look. 👍

THANK YOU!
i might be not understand how this module so far, now i understand how this work i guess :>
thankyou for awesone module!

**Comment by juicycool92** [comment]
> Hi @juicycool92,
> 
> Right now you can add headers for the request [like this example](https://github.com/BRIKEV/express-jsdoc-swagger/blob/master/examples/parameters/headers.js) as you mentioned in this issue. However, for responses we currently don't have support for that with the comments but you can use our [merge option](https://brikev.github.io/express-jsdoc-swagger-docs/#/merge). Maybe that can help you to solve your issue in the meantime.
> 
> For the response headers, there is already an issue and a discussion on the best way to create comments in [this issue](https://github.com/BRIKEV/express-jsdoc-swagger/issues/92).
> 
> We will keep this issue to track the header's examples feature progress. I don't think there is a way to create those examples right now. 🤔 we will have a look. 👍

Thanks to reply again!
Finally I start written docs according to your [merge option](https://brikev.github.io/express-jsdoc-swagger-docs/#/merge) method after receive your reply, and its seems perfect!
But I cannot try it out on front-end. it's work, but request body's are always empty!

this is my `swagger.json` file
```
...
"/user/validUserId": {
      "post": {
        "tags": [
          "user",
          "app"
        ],
        "consumes": "application/json",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "description": "아이디 중복 체크 바디",
            "schema": {
              "$ref": "#/parameters/req-body/user-valid-user-id"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/responses/default-res"
                }
              }
            }
          }
        }
      }
    },
...
```

and front side result is this

![image](https://user-images.githubusercontent.com/12273678/97888513-8f235e80-1d6e-11eb-95f4-819433e9bc0a.png)
<Ah! seems like just perfect!>

but when I try it out,

![image](https://user-images.githubusercontent.com/12273678/97888621-ad895a00-1d6e-11eb-8c77-14e3d996db80.png)
<oops..?>

this is not what I expect. My body is gone.
I assume that `Content-Type` is not correctly set to `application/json`, therefore it wont read body data properly I guess.

my expect curl is this
`curl -X POST "http://localhost:3000/user/validUserId" -H "Content-Type:application/json" -H  "accept: application/json" -d "{\"userId\":\"some_test_mail@foo.com\"}"`

I reference on [swagger editor](https://editor.swagger.io/) for add `Content-Type` to request header.
guess `consumes` are keyword, but no luck.

Sorry for bothering you, but I'm stuck again.. struggling at this issue for several hours and Im done..
can you give me little bit of more hint?

Thanks!

**Comment by juicycool92** [comment]
Sorry, all I need is just fresh air and rest guess.
this morning, I restart investing how swagger json work, and I figured out that requestBody is need to be separated between parameters! my bad 😭 

just is case like my case, I leave codes below.

this is previous code
```
"/user/validUserId": {
      "post": {
        "tags": [
          "user",
          "app"
        ],
        "consumes": "application/json",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "description": "아이디 중복 체크 바디",
            "schema": {
              "$ref": "#/parameters/req-body/user-valid-user-id"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/responses/default-res"
                }
              }
            }
          }
        }
      }
    },
```

and this is what i change
```
"/user/validUserId": {
      "post": {
        "tags": [
          "user",
          "app"
        ],
        "operationId": "addPet",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "requestBody" : {
          "required": true,
          "description": "아이디 중복 체크 바디",
          "content" : {
            "application/json" : {
              "schema": {
                "$ref": "#/parameters/req-body/user-valid-user-id"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/responses/default-res"
                }
              }
            }
          }
        }
      }
    },
```
in case if you want to append requestHeader,
```
"/user/validUserId": {
      "post": {
        "tags": [
          "user",
          "app"
        ],
        "operationId": "addPet",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "$ref": "#/parameters/x-lang"
          }
        ],
        "requestBody" : {
          "required": true,
          "description": "아이디 중복 체크 바디",
          "content" : {
            "application/json" : {
              "schema": {
                "$ref": "#/parameters/req-body/user-valid-user-id"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/responses/default-res"
                }
              }
            }
          }
        }
      }
    },
```

![image](https://user-images.githubusercontent.com/12273678/97938810-c2dda300-1dc5-11eb-8361-c579c5741087.png)
<result front end view>

![image](https://user-images.githubusercontent.com/12273678/97938854-dd178100-1dc5-11eb-853c-f8a13b0bb538.png)
<now, curl is successfully append header PLUS body!>

sorry for bothering you!
this module is awesome indeed!

**Comment by kevinccbsg** [comment]
Thanks for adding the solution to this issue. 🎉
