### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by connorads** [BRIKEV/express-jsdoc-swagger#99]
Any way to get TypeScript working with this?

> node_modules/express-jsdoc-swagger/index.js' implicitly has an 'any' type.
  Try `npm install @types/express-jsdoc-swagger` if it exists or add a new declaration (.d.ts) file containing `declare module 'express-jsdoc-swagger';`ts(7016)

> yarn add @types/express-jsdoc-swagger
yarn add v1.22.5
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@types%2fexpress-jsdoc-swagger: Not found".

**Comment by saeidalidadi** [comment]
I can work on this, currently I am working on an express project with typescript and I am happy to have this feature on my api project.

**Comment by kevinccbsg** [comment]
Hi @saeidalidadi and @connorads,

We are working on this in this branch https://github.com/BRIKEV/express-jsdoc-swagger/tree/fix/ts-support to merge this. After we merge that we will create a new release 👍
